package com.aston.group.stationdefender.actors;

import com.aston.group.stationdefender.config.Constants;

/**
 * Fast Alien with slow, but high damage.
 *
 * @author IngramJ
 *         <p>
 *         TODO Individual Class for testing purposes.
 *         Remove this class and have it generated by the factory.
 */
public class CloseCombatAlien extends Alien {

    public CloseCombatAlien() {
        this(0, 0);
    }

    public CloseCombatAlien(int x, int y) {
        super("Close Combat Alien", 2, 60.0, 2, Constants.UNIT_HEALTH, 1, 7.0, x, y, 20, 20);
    }
}